# Generated by Django 5.2.12 on 2026-03-30 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_user_passage_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='full_name',
        ),
    ]
