# Generated by Django 5.2.12 on 2026-04-01 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_providerprofile_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('breed', models.CharField(blank=True, max_length=50, null=True)),
                ('size', models.CharField(choices=[('p', 'Pequeno'), ('m', 'Médio'), ('g', 'Grande')], max_length=1)),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('vaccination_status', models.CharField(choices=[('p', 'Pendente'), ('c', 'Atualizado')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='core.clientprofile')),
            ],
        ),
    ]
