# Generated by Django 5.2.12 on 2026-04-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='providerprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
