# Generated by Django 5.2.12 on 2026-04-01 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_clientprofile_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em andamento'), ('finished', 'Concluído')], default='pending', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.pet')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.providerprofile')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.servicetype')),
            ],
        ),
    ]
