# Generated by Django 5.2.12 on 2026-04-02 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='core.pet'),
        ),
        migrations.AlterField(
            model_name='service',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='core.providerprofile'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='core.servicetype'),
        ),
    ]
