# Generated by Django 5.2.13 on 2026-05-11 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_pet_pet_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('paid_at', models.DateTimeField()),
                ('created_at', models.DateField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.service')),
            ],
        ),
    ]
