# Generated by Django 5.2.13 on 2026-08-06 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='vaccination_status',
        ),
    ]
