# Generated by Django 5.2.13 on 2026-08-28 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_pet_vaccination_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='pet',
        ),
        migrations.AddField(
            model_name='service',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='core.clientprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='pets',
            field=models.ManyToManyField(related_name='services', to='core.pet'),
        ),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[(1, 'Em análise'), (2, 'Confirmado'), (3, 'Em andamento'), (4, 'Concluído'), (5, 'Cancelado'), (6, 'Recusado')], default=1, max_length=20),
        ),
    ]
