# Generated by Django 5.2.13 on 2026-09-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_servicelocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.IntegerField(choices=[(1, 'Em análise'), (2, 'Confirmado'), (3, 'Em andamento'), (4, 'Concluído'), (5, 'Cancelado'), (6, 'Recusado')], default=1, max_length=20),
        ),
    ]
