# Generated by Django 5.2.13 on 2026-09-30 22:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0023_provideravailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
