# Generated by Django 5.2.13 on 2026-09-28 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_service_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
