# Generated by Django 5.2.13 on 2026-10-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_service_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_rating',
            field=models.BooleanField(default=False),
        ),
    ]
